### ISSUE TITLE
npm run vtu error

### ISSUE THREAD

**Issue by universeroc** [neatfx/tiny-evt#32]
$ npm run build-dev-runner && NODE_ENV=development TEST=vtu node build/dev-runner.js

> tiny-evt@0.16.2 build-dev-runner
> cat scripts/args.esbuild.dev-runner | xargs npx esbuild

  build/dev-runner.js  190.9kb

vite v2.8.2 building for production...
✓ 253 modules transformed.
tests/vtu/build/Navbar.spec.532c1d20.js    1.50 KiB / gzip: 0.69 KiB
tests/vtu/build/Navbar.spec.9ce7a654.css   0.30 KiB / gzip: 0.19 KiB
tests/vtu/build/vendor.39ff42b6.js         476.07 KiB / gzip: 153.33 KiB
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn jest ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:475:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:475:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn jest',
  path: 'jest',
  spawnargs: [ '--config', 'configs/jest.config.vtu.json' ]
}

Node.js v17.2.0
error Command failed with exit code 1.

**Comment by universeroc** [comment]
after install jest globally it's OK but got another error

> tiny-evt@0.16.2 vtu
> npm run build-dev-runner && NODE_ENV=development TEST=vtu node build/dev-runner.js


> tiny-evt@0.16.2 build-dev-runner
> cat scripts/args.esbuild.dev-runner | xargs npx esbuild


  build/dev-runner.js  190.9kb

⚡ Done in 23ms
vite v2.8.2 building for production...
✓ 253 modules transformed.
tests/vtu/build/Navbar.spec.532c1d20.js    1.50 KiB / gzip: 0.69 KiB
tests/vtu/build/Navbar.spec.9ce7a654.css   0.30 KiB / gzip: 0.19 KiB
tests/vtu/build/vendor.39ff42b6.js         476.07 KiB / gzip: 153.33 KiB
 FAIL  tests/vtu/build/Navbar.spec.532c1d20.js
  ● Test suite failed to run

    TypeError: Object prototype may only be an Object or null: undefined
        at Function.setPrototypeOf (<anonymous>)

      368 |  `,a(s.gutter,w.replace(/\d/g," "))," ",N,a(s.marker,"^").repeat(v)].join(""),k&&n.message&&(P+=" "+a(s.message,n.message))}return[a(s.marker,">"),a(s.gutter,w),_.length>0?` ${_}`:"",P].join("")}else return` ${a(s.gutter,w)}${_.length>0?` ${_}`:""}`}).join(`
      369 | `);return n.message&&!f&&(h=`${" ".repeat(p+1)}${n.message}
    > 370 | ${h}`),r?i.reset(h):h}function gN(e,t,n,r={}){if(!zd){zd=!0;const s="Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.";if(process.emitWarning)process.emitWarning(s,"DeprecationWarning");else{const a=new Error(s);a.name="DeprecationWarning",console.warn(new Error(s))}}return n=Math.max(n,0),B1(e,{start:{column:n,line:t}},r)}var zn=Gt,mN=process.cwd,bo=null,bN=process.platform;process.cwd=function(){return bo||(bo=mN.call(process)),bo};try{process.cwd()}catch{}if(typeof process.chdir=="function"){var Xd=process.chdir;process.chdir=function(e){bo=null,Xd.call(process,e)},Object.setPrototypeOf&&Object.setPrototypeOf(process.chdir,Xd)}var yN=vN;function vN(e){zn.hasOwnProperty("O_SYMLINK")&&process.version.match(/^v0\.6\.[0-2]|^v0\.5\./)&&t(e),e.lutimes||n(e),e.chown=s(e.chown),e.fchown=s(e.fchown),e.lchown=s(e.lchown),e.chmod=r(e.chmod),e.fchmod=r(e.fchmod),e.lchmod=r(e.lchmod),e.chownSync=a(e.chownSync),e.fchownSync=a(e.fchownSync),e.lchownSync=a(e.lchownSync),e.chmodSync=i(e.chmodSync),e.fchmodSync=i(e.fchmodSync),e.lchmodSync=i(e.lchmodSync),e.stat=o(e.stat),e.fstat=o(e.fstat),e.lstat=o(e.lstat),e.statSync=u(e.statSync),e.fstatSync=u(e.fstatSync),e.lstatSync=u(e.lstatSync),e.lchmod||(e.lchmod=function(c,f,p){p&&process.nextTick(p)},e.lchmodSync=function(){}),e.lchown||(e.lchown=function(c,f,p,d){d&&process.nextTick(d)},e.lchownSync=function(){}),bN==="win32"&&(e.rename=function(c){return function(f,p,d){var h=Date.now(),_=0;c(f,p,function g(m){if(m&&(m.code==="EACCES"||m.code==="EPERM")&&Date.now()-h<6e4){setTimeout(function(){e.stat(p,function(b,w){b&&b.code==="ENOENT"?c(f,p,g):d(m)})},_),_<100&&(_+=10);return}d&&d(m)})}}(e.rename)),e.read=function(c){function f(p,d,h,_,g,m){var b;if(m&&typeof m=="function"){var w=0;b=function(O,k,P){if(O&&O.code==="EAGAIN"&&w<10)return w++,c.call(e,p,d,h,_,g,b);m.apply(this,arguments)}}return c.call(e,p,d,h,_,g,b)}return Object.setPrototypeOf&&Object.setPrototypeOf(f,c),f}(e.read),e.readSync=function(c){return function(f,p,d,h,_){for(var g=0;;)try{return c.call(e,f,p,d,h,_)}catch(m){if(m.code==="EAGAIN"&&g<10){g++;continue}throw m}}}(e.readSync);function t(c){c.lchmod=function(f,p,d){c.open(f,zn.O_WRONLY|zn.O_SYMLINK,p,function(h,_){if(h){d&&d(h);return}c.fchmod(_,p,function(g){c.close(_,function(m){d&&d(g||m)})})})},c.lchmodSync=function(f,p){var d=c.openSync(f,zn.O_WRONLY|zn.O_SYMLINK,p),h=!0,_;try{_=c.fchmodSync(d,p),h=!1}finally{if(h)try{c.closeSync(d)}catch{}else c.closeSync(d)}return _}}function n(c){zn.hasOwnProperty("O_SYMLINK")?(c.lutimes=function(f,p,d,h){c.open(f,zn.O_SYMLINK,function(_,g){if(_){h&&h(_);return}c.futimes(g,p,d,function(m){c.close(g,function(b){h&&h(m||b)})})})},c.lutimesSync=function(f,p,d){var h=c.openSync(f,zn.O_SYMLINK),_,g=!0;try{_=c.futimesSync(h,p,d),g=!1}finally{if(g)try{c.closeSync(h)}catch{}else c.closeSync(h)}return _}):(c.lutimes=function(f,p,d,h){h&&process.nextTick(h)},c.lutimesSync=function(){})}function r(c){return c&&function(f,p,d){return c.call(e,f,p,function(h){l(h)&&(h=null),d&&d.apply(this,arguments)})}}function i(c){return c&&function(f,p){try{return c.call(e,f,p)}catch(d){if(!l(d))throw d}}}function s(c){return c&&function(f,p,d,h){return c.call(e,f,p,d,function(_){l(_)&&(_=null),h&&h.apply(this,arguments)})}}function a(c){return c&&function(f,p,d){try{return c.call(e,f,p,d)}catch(h){if(!l(h))throw h}}}function o(c){return c&&function(f,p,d){typeof p=="function"&&(d=p,p=null);function h(_,g){g&&(g.uid<0&&(g.uid+=4294967296),g.gid<0&&(g.gid+=4294967296)),d&&d.apply(this,arguments)}return p?c.call(e,f,p,h):c.call(e,f,h)}}function u(c){return c&&function(f,p){var d=p?c.call(e,f,p):c.call(e,f);return d&&(d.uid<0&&(d.uid+=4294967296),d.gid<0&&(d.gid+=4294967296)),d}}function l(c){if(!c||c.code==="ENOSYS")return!0;var f=!process.getuid||process.getuid()!==0;return!!(f&&(c.code==="EINVAL"||c.code==="EPERM"))}}var Qd=Gt.Stream,EN=wN;function wN(e){return{ReadStream:t,WriteStream:n};function t(r,i){if(!(this instanceof t))return new t(r,i);Qd.call(this);var s=this;this.path=r,this.fd=null,this.readable=!0,this.paused=!1,this.flags="r",this.mode=438,this.bufferSize=64*1024,i=i||{};for(var a=Object.keys(i),o=0,u=a.length;o<u;o++){var l=a[o];this[l]=i[l]}if(this.encoding&&this.setEncoding(this.encoding),this.start!==void 0){if(typeof this.start!="number")throw TypeError("start must be a Number");if(this.end===void 0)this.end=1/0;else if(typeof this.end!="number")throw TypeError("end must be a Number");if(this.start>this.end)throw new Error("start must be <= end");this.pos=this.start}if(this.fd!==null){process.nextTick(function(){s._read()});return}e.open(this.path,this.flags,this.mode,function(c,f){if(c){s.emit("error",c),s.readable=!1;return}s.fd=f,s.emit("open",f),s._read()})}function n(r,i){if(!(this instanceof n))return new n(r,i);Qd.call(this),this.path=r,this.fd=null,this.writable=!0,this.flags="w",this.encoding="binary",this.mode=438,this.bytesWritten=0,i=i||{};for(var s=Object.keys(i),a=0,o=s.length;a<o;a++){var u=s[a];this[u]=i[u]}if(this.start!==void 0){if(typeof this.start!="number")throw TypeError("start must be a Number");if(this.start<0)throw new Error("start must be >= zero");this.pos=this.start}this.busy=!1,this._queue=[],this.fd===null&&(this._open=e.open,this._queue.push([this._open,this.path,this.flags,this.mode,void 0]),this.flush())}}var RN=CN,SN=Object.getPrototypeOf||function(e){return e.__proto__};function CN(e){if(e===null||typeof e!="object")return e;if(e instanceof Object)var t={__proto__:SN(e)};else var t=Object.create(null);return Object.getOwnPropertyNames(e).forEach(function(n){Object.defineProperty(t,n,Object.getOwnPropertyDescriptor(e,n))}),t}var Ve=Gt,ON=yN,TN=EN,AN=RN,ao=Gt,at,Qo;typeof Symbol=="function"&&typeof Symbol.for=="function"?(at=Symbol.for("graceful-fs.queue"),Qo=Symbol.for("graceful-fs.previous")):(at="___graceful-fs.queue",Qo="___graceful-fs.previous");function NN(){}function j1(e,t){Object.defineProperty(e,at,{get:function(){return t}})}var Yr=NN;ao.debuglog?Yr=ao.debuglog("gfs4"):/\bgfs4\b/i.test("")&&(Yr=function(){var e=ao.format.apply(ao,arguments);e="GFS4: "+e.split(/\n/).join(`
          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^
      371 | GFS4: `),console.error(e)});if(!Ve[at]){var $N=_c[at]||[];j1(Ve,$N),Ve.close=function(e){function t(n,r){return e.call(Ve,n,function(i){i||Yd(),typeof r=="function"&&r.apply(this,arguments)})}return Object.defineProperty(t,Qo,{value:e}),t}(Ve.close),Ve.closeSync=function(e){function t(n){e.apply(Ve,arguments),Yd()}return Object.defineProperty(t,Qo,{value:e}),t}(Ve.closeSync),/\bgfs4\b/i.test("")&&process.on("exit",function(){Yr(Ve[at]),Gt.equal(Ve[at].length,0)})}_c[at]||j1(_c,Ve[at]);var xN=H1(AN(Ve));function H1(e){ON(e),e.gracefulify=H1,e.createReadStream=O,e.createWriteStream=k;var t=e.readFile;e.readFile=n;function n(v,A,M){return typeof A=="function"&&(M=A,A=null),E(v,A,M);function E($,x,j,T){return t($,x,function(S){S&&(S.code==="EMFILE"||S.code==="ENFILE")?gi([E,[$,x,j],S,T||Date.now(),Date.now()]):typeof j=="function"&&j.apply(this,arguments)})}}var r=e.writeFile;e.writeFile=i;function i(v,A,M,E){return typeof M=="function"&&(E=M,M=null),$(v,A,M,E);function $(x,j,T,S,q){return r(x,j,T,function(H){H&&(H.code==="EMFILE"||H.code==="ENFILE")?gi([$,[x,j,T,S],H,q||Date.now(),Date.now()]):typeof S=="function"&&S.apply(this,arguments)})}}var s=e.appendFile;s&&(e.appendFile=a);function a(v,A,M,E){return typeof M=="function"&&(E=M,M=null),$(v,A,M,E);function $(x,j,T,S,q){return s(x,j,T,function(H){H&&(H.code==="EMFILE"||H.code==="ENFILE")?gi([$,[x,j,T,S],H,q||Date.now(),Date.now()]):typeof S=="function"&&S.apply(this,arguments)})}}var o=e.copyFile;o&&(e.copyFile=u);function u(v,A,M,E){return typeof M=="function"&&(E=M,M=0),$(v,A,M,E);function $(x,j,T,S,q){return o(x,j,T,function(H){H&&(H.code==="EMFILE"||H.code==="ENFILE")?gi([$,[x,j,T,S],H,q||Date.now(),Date.now()]):typeof S=="function"&&S.apply(this,arguments)})}}var l=e.readdir;e.readdir=c;function c(v,A,M){return typeof A=="function"&&(M=A,A=null),E(v,A,M);function E($,x,j,T){return l($,x,function(S,q){S&&(S.code==="EMFILE"||S.code==="ENFILE")?gi([E,[$,x,j],S,T||Date.now(),Date.now()]):(q&&q.sort&&q.sort(),typeof j=="function"&&j.call(this,S,q))})}}if(process.version.substr(0,4)==="v0.8"){var f=TN(e);g=f.ReadStream,b=f.WriteStream}var p=e.ReadStream;p&&(g.prototype=Object.create(p.prototype),g.prototype.open=m);var d=e.WriteStream;d&&(b.prototype=Object.create(d.prototype),b.prototype.open=w),Object.defineProperty(e,"ReadStream",{get:function(){return g},set:function(v){g=v},enumerable:!0,configurable:!0}),Object.defineProperty(e,"WriteStream",{get:function(){return b},set:function(v){b=v},enumerable:!0,configurable:!0});var h=g;Object.defineProperty(e,"FileReadStream",{get:function(){return h},set:function(v){h=v},enumerable:!0,configurable:!0});var _=b;Object.defineProperty(e,"FileWriteStream",{get:function(){return _},set:function(v){_=v},enumerable:!0,configurable:!0});function g(v,A){return this instanceof g?(p.apply(this,arguments),this):g.apply(Object.create(g.prototype),arguments)}function m(){var v=this;N(v.path,v.flags,v.mode,function(A,M){A?(v.autoClose&&v.destroy(),v.emit("error",A)):(v.fd=M,v.emit("open",M),v.read())})}function b(v,A){return this instanceof b?(d.apply(this,arguments),this):b.apply(Object.create(b.prototype),arguments)}function w(){var v=this;N(v.path,v.flags,v.mode,function(A,M){A?(v.destroy(),v.emit("error",A)):(v.fd=M,v.emit("open",M))})}function O(v,A){return new e.ReadStream(v,A)}function k(v,A){return new e.WriteStream(v,A)}var P=e.open;e.open=N;function N(v,A,M,E){return typeof M=="function"&&(E=M,M=null),$(v,A,M,E);function $(x,j,T,S,q){return P(x,j,T,function(H,_e){H&&(H.code==="EMFILE"||H.code==="ENFILE")?gi([$,[x,j,T,S],H,q||Date.now(),Date.now()]):typeof S=="function"&&S.apply(this,arguments)})}}return e}function gi(e){Yr("ENQUEUE",e[0].name,e[1]),Ve[at].push(e),hp()}var oo;function Yd(){for(var e=Date.now(),t=0;t<Ve[at].length;++t)Ve[at][t].length>2&&(Ve[at][t][3]=e,Ve[at][t][4]=e);hp()}function hp(){if(clearTimeout(oo),oo=void 0,Ve[at].length!==0){var e=Ve[at].shift(),t=e[0],n=e[1],r=e[2],i=e[3],s=e[4];if(i===void 0)Yr("RETRY",t.name,n),t.apply(null,n);else if(Date.now()-i>=6e4){Yr("TIMEOUT",t.name,n);var a=n.pop();typeof a=="function"&&a.call(null,r)}else{var o=Date.now()-s,u=Math.max(s-i,1),l=Math.min(u*1.2,100);o>=l?(Yr("RETRY",t.name,n),t.apply(null,n.concat([i]))):Ve[at].push(e)}oo===void 0&&(oo=setTimeout(hp,0))}}var Xu={};(function(e){e.isInteger=t=>typeof t=="number"?Number.isInteger(t):typeof t=="string"&&t.trim()!==""?Number.isInteger(Number(t)):!1,e.find=(t,n)=>t.nodes.find(r=>r.type===n),e.exceedsLimit=(t,n,r=1,i)=>i===!1||!e.isInteger(t)||!e.isInteger(n)?!1:(Number(n)-Number(t))/Number(r)>=i,e.escapeNode=(t,n=0,r)=>{let i=t.nodes[n];!i||(r&&i.type===r||i.type==="open"||i.type==="close")&&i.escaped!==!0&&(i.value="\\"+i.value,i.escaped=!0)},e.encloseBrace=t=>t.type!=="brace"?!1:t.commas>>0+t.ranges>>0===0?(t.invalid=!0,!0):!1,e.isInvalidBrace=t=>t.type!=="brace"?!1:t.invalid===!0||t.dollar?!0:t.commas>>0+t.ranges>>0===0||t.open!==!0||t.close!==!0?(t.invalid=!0,!0):!1,e.isOpenOrClose=t=>t.type==="open"||t.type==="close"?!0:t.open===!0||t.close===!0,e.reduce=t=>t.reduce((n,r)=>(r.type==="text"&&n.push(r.value),r.type==="range"&&(r.type="text"),n),[]),e.flatten=(...t)=>{const n=[],r=i=>{for(let s=0;s<i.length;s++){let a=i[s];Array.isArray(a)?r(a):a!==void 0&&n.push(a)}return n};return r(t),n}})(Xu);const Jd=Xu;var dp=(e,t={})=>{let n=(r,i={})=>{let s=t.escapeInvalid&&Jd.isInvalidBrace(i),a=r.invalid===!0&&t.escapeInvalid===!0,o="";if(r.value)return(s||a)&&Jd.isOpenOrClose(r)?"\\"+r.value:r.value;if(r.value)return r.value;if(r.nodes)for(let u of r.nodes)o+=n(u);return o};return n(e)};/*!
      372 |  * is-number <https://github.com/jonschlinkert/is-number>
      373 |  *

      at ../tests/vtu/build/vendor.39ff42b6.js:370:1970
      at ON (../tests/vtu/build/vendor.39ff42b6.js:370:1720)
      at H1 (../tests/vtu/build/vendor.39ff42b6.js:371:524)
      at Object.<anonymous> (../tests/vtu/build/vendor.39ff42b6.js:371:498)
      at Object.<anonymous> (../tests/vtu/build/Navbar.spec.532c1d20.js:1:295)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.95 s
Ran all test suites.
